# Module 12 Challenge
## Deliverable 2: Scrape and Analyze Mars Weather Data

In [1]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as BeautifulSoup
import matplotlib.pyplot as plt
import pandas as pd
from pprint import pprint

In [2]:
browser = Browser('chrome')

### Step 1: Visit the Website

Use automated browsing to visit the [Mars Temperature Data Site](https://static.bc-edx.com/data/web/mars_facts/temperature.html). Inspect the page to identify which elements to scrape.

   > **Hint** To identify which elements to scrape, you might want to inspect the page by using Chrome DevTools to discover whether the table contains usable classes.

In [3]:
# Visit the website
# https://static.bc-edx.com/data/web/mars_facts/temperature.html
url = "https://static.bc-edx.com/data/web/mars_facts/temperature.html"
browser.visit(url)

### Step 2: Scrape the Table

Create a Beautiful Soup object and use it to scrape the data in the HTML table.

Note that this can also be achieved by using the Pandas `read_html` function. However, use Beautiful Soup here to continue sharpening your web scraping skills.

In [4]:
# Create a Beautiful Soup Object
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [5]:
# Extract all rows of data
table = soup.find_all('tr',class_ = 'data-row')
for rows in table:
    print(rows)

<tr class="data-row">
<td>2</td>
<td>2012-08-16</td>
<td>10</td>
<td>155</td>
<td>6</td>
<td>-75.0</td>
<td>739.0</td>
</tr>
<tr class="data-row">
<td>13</td>
<td>2012-08-17</td>
<td>11</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>24</td>
<td>2012-08-18</td>
<td>12</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>35</td>
<td>2012-08-19</td>
<td>13</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>732.0</td>
</tr>
<tr class="data-row">
<td>46</td>
<td>2012-08-20</td>
<td>14</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>57</td>
<td>2012-08-21</td>
<td>15</td>
<td>158</td>
<td>6</td>
<td>-78.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>68</td>
<td>2012-08-22</td>
<td>16</td>
<td>158</td>
<td>6</td>
<td>-77.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>79</td>
<td>2012-08-23</td>
<td>17</td>
<td>159</td>
<td>6</td>
<td>-76.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>112</td>
<td>2012-08-27</td>
<td>21</td>
<td>161</td>
<td>6</td>
<td>-74.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>114</td>
<td>2012-08-28</td>
<td>22</td>
<td>162</td>
<td>6</td>
<td>-74.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>123</td>
<td>2012-08-29</td>
<td>23</td>
<td>162</td>
<td>6</td>
<td>-75.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>134</td>
<td>2012-08-30</td>
<td>24</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>145</td>
<td>2012-08-31</td>
<td>25</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>156</td>
<td>2012-09-01</td>
<td>26</td>
<td>164</td>
<td>6</td>
<td>-76.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>163</td>
<td>2012-09-02</td>
<td>27</td>
<td>164</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>170</td>
<td>2012-09-03</td>
<td>28</td>
<td>165</td>
<td>6</td>
<td>-75.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>171</td>
<td>2012-09-04</td>
<td>29</td>
<td>166</td>
<td>6</td>
<td>-75.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>172</td>
<td>2012-09-05</td>
<td>30</td>
<td>166</td>
<td>6</td>
<td>-74.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>173</td>
<td>2012-09-06</td>
<td>31</td>
<td>167</td>
<td>6</td>
<td>-74.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>175</td>
<td>2012-09-08</td>
<td>33</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>176</td>
<td>2012-09-10</td>
<td>34</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>177</td>
<td>2012-09-11</td>
<td>35</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>749.0</td>
</tr>
<tr class="data-row">
<td>178</td>
<td>2012-09-12</td>
<td>36</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>179</td>
<td>2012-09-13</td>
<td>37</td>
<td>170</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>180</td>
<td>2012-09-14</td>
<td>38</td>
<td>171</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>181</td>
<td>2012-09-15</td>
<td>39</td>
<td>171</td>
<td>6</td>
<td>-75.0</td>
<td>751.0</td>
</tr>
<tr class="data-row">
<td>182</td>
<td>2012-09-16</td>
<td>40</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>183</td>
<td>2012-09-17</td>
<td>41</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>184</td>
<td>2012-09-18</td>
<td>42</td>
<td>173</td>
<td>6</td>
<td>-75.0</td>
<td>754.0</td>
</tr>
<tr class="data-row">
<td>185</td>
<td>2012-09-19</td>
<td>43</td>
<td>173</td>
<td>6</td>
<td>-74.0</td>
<td>756.0</td>
</tr>
<tr class="data-row">
<td>186</td>
<td>2012-09-20</td>
<td>44</td>
<td>174</td>
<td>6</td>
<td>-75.0</td>
<td>757.0</td>
</tr>
<tr class="data-row">
<td>187</td>
<td>2012-09-21</td>
<td>45</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>188</td>
<td>2012-09-22</td>
<td>46</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>189</td>
<td>2012-09-23</td>
<td>47</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>190</td>
<td>2012-09-24</td>
<td>48</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>759.0</td>
</tr>
<tr class="data-row">
<td>191</td>
<td>2012-09-25</td>
<td>49</td>
<td>177</td>
<td>6</td>
<td>-74.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>192</td>
<td>2012-09-26</td>
<td>50</td>
<td>177</td>
<td>6</td>
<td>-72.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>193</td>
<td>2012-09-27</td>
<td>51</td>
<td>178</td>
<td>6</td>
<td>-76.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>194</td>
<td>2012-09-28</td>
<td>52</td>
<td>179</td>
<td>6</td>
<td>-74.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>195</td>
<td>2012-09-29</td>
<td>53</td>
<td>179</td>
<td>6</td>
<td>-71.0</td>
<td>764.0</td>
</tr>
<tr class="data-row">
<td>196</td>
<td>2012-09-30</td>
<td>54</td>
<td>180</td>
<td>7</td>
<td>-72.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>197</td>
<td>2012-10-01</td>
<td>55</td>
<td>180</td>
<td>7</td>
<td>-74.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>198</td>
<td>2012-10-02</td>
<td>56</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>768.0</td>
</tr>
<tr class="data-row">
<td>199</td>
<td>2012-10-03</td>
<td>57</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>200</td>
<td>2012-10-04</td>
<td>58</td>
<td>182</td>
<td>7</td>
<td>-74.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>201</td>
<td>2012-10-05</td>
<td>59</td>
<td>183</td>
<td>7</td>
<td>-76.0</td>
<td>771.0</td>
</tr>
<tr class="data-row">
<td>202</td>
<td>2012-10-06</td>
<td>60</td>
<td>183</td>
<td>7</td>
<td>-75.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>203</td>
<td>2012-10-07</td>
<td>61</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>204</td>
<td>2012-10-08</td>
<td>62</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>774.0</td>
</tr>
<tr class="data-row">
<td>205</td>
<td>2012-10-09</td>
<td>63</td>
<td>185</td>
<td>7</td>
<td>-73.0</td>
<td>775.0</td>
</tr>
<tr class="data-row">
<td>206</td>
<td>2012-10-10</td>
<td>64</td>
<td>186</td>
<td>7</td>
<td>-74.0</td>
<td>776.0</td>
</tr>
<tr class="data-row">
<td>207</td>
<td>2012-10-11</td>
<td>65</td>
<td>186</td>
<td>7</td>
<td>-72.0</td>
<td>777.0</td>
</tr>
<tr class="data-row">
<td>208</td>
<td>2012-10-12</td>
<td>66</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>209</td>
<td>2012-10-13</td>
<td>67</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>780.0</td>
</tr>
<tr class="data-row">
<td>210</td>
<td>2012-10-14</td>
<td>68</td>
<td>188</td>
<td>7</td>
<td>-71.0</td>
<td>781.0</td>
</tr>
<tr class="data-row">
<td>211</td>
<td>2012-10-15</td>
<td>69</td>
<td>189</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>212</td>
<td>2012-10-17</td>
<td>70</td>
<td>189</td>
<td>7</td>
<td>-72.0</td>
<td>783.0</td>
</tr>
<tr class="data-row">
<td>213</td>
<td>2012-10-18</td>
<td>71</td>
<td>190</td>
<td>7</td>
<td>-71.0</td>
<td>784.0</td>
</tr>
<tr class="data-row">
<td>214</td>
<td>2012-10-19</td>
<td>72</td>
<td>190</td>
<td>7</td>
<td>-73.0</td>
<td>785.0</td>
</tr>
<tr class="data-row">
<td>215</td>
<td>2012-10-20</td>
<td>73</td>
<td>191</td>
<td>7</td>
<td>-70.0</td>
<td>788.0</td>
</tr>
<tr class="data-row">
<td>216</td>
<td>2012-10-21</td>
<td>74</td>
<td>192</td>
<td>7</td>
<td>-72.0</td>
<td>790.0</td>
</tr>
<tr class="data-row">
<td>217</td>
<td>2012-10-22</td>
<td>75</td>
<td>192</td>
<td>7</td>
<td>-73.0</td>
<td>791.0</td>
</tr>
<tr class="data-row">
<td>218</td>
<td>2012-10-23</td>
<td>76</td>
<td>193</td>
<td>7</td>
<td>-73.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>219</td>
<td>2012-10-24</td>
<td>77</td>
<td>193</td>
<td>7</td>
<td>-71.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>220</td>
<td>2012-10-25</td>
<td>78</td>
<td>194</td>
<td>7</td>
<td>-71.0</td>
<td>793.0</td>
</tr>
<tr class="data-row">
<td>221</td>
<td>2012-10-26</td>
<td>79</td>
<td>195</td>
<td>7</td>
<td>-73.0</td>
<td>795.0</td>
</tr>
<tr class="data-row">
<td>222</td>
<td>2012-10-27</td>
<td>80</td>
<td>195</td>
<td>7</td>
<td>-70.0</td>
<td>796.0</td>
</tr>
<tr class="data-row">
<td>223</td>
<td>2012-10-28</td>
<td>81</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>798.0</td>
</tr>
<tr class="data-row">
<td>224</td>
<td>2012-10-29</td>
<td>82</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>799.0</td>
</tr>
<tr class="data-row">
<td>225</td>
<td>2012-10-30</td>
<td>83</td>
<td>197</td>
<td>7</td>
<td>-72.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>226</td>
<td>2012-10-31</td>
<td>84</td>
<td>198</td>
<td>7</td>
<td>-70.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>227</td>
<td>2012-11-01</td>
<td>85</td>
<td>198</td>
<td>7</td>
<td>-71.0</td>
<td>805.0</td>
</tr>
<tr class="data-row">
<td>228</td>
<td>2012-11-02</td>
<td>86</td>
<td>199</td>
<td>7</td>
<td>-71.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>229</td>
<td>2012-11-03</td>
<td>87</td>
<td>199</td>
<td>7</td>
<td>-70.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>230</td>
<td>2012-11-04</td>
<td>88</td>
<td>200</td>
<td>7</td>
<td>-70.0</td>
<td>811.0</td>
</tr>
<tr class="data-row">
<td>231</td>
<td>2012-11-05</td>
<td>89</td>
<td>201</td>
<td>7</td>
<td>-73.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>233</td>
<td>2012-11-06</td>
<td>90</td>
<td>201</td>
<td>7</td>
<td>-71.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>234</td>
<td>2012-11-07</td>
<td>91</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>817.0</td>
</tr>
<tr class="data-row">
<td>235</td>
<td>2012-11-08</td>
<td>92</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>820.0</td>
</tr>
<tr class="data-row">
<td>236</td>
<td>2012-11-09</td>
<td>93</td>
<td>203</td>
<td>7</td>
<td>-72.0</td>
<td>819.0</td>
</tr>
<tr class="data-row">
<td>237</td>
<td>2012-11-10</td>
<td>94</td>
<td>204</td>
<td>7</td>
<td>-70.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>238</td>
<td>2012-11-11</td>
<td>95</td>
<td>204</td>
<td>7</td>
<td>-68.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>239</td>
<td>2012-11-12</td>
<td>96</td>
<td>205</td>
<td>7</td>
<td>-71.0</td>
<td>826.0</td>
</tr>
<tr class="data-row">
<td>240</td>
<td>2012-11-13</td>
<td>97</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>241</td>
<td>2012-11-14</td>
<td>98</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>242</td>
<td>2012-11-15</td>
<td>99</td>
<td>207</td>
<td>7</td>
<td>-68.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>3</td>
<td>2012-11-16</td>
<td>100</td>
<td>207</td>
<td>7</td>
<td>-66.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>4</td>
<td>2012-11-17</td>
<td>101</td>
<td>208</td>
<td>7</td>
<td>-65.0</td>
<td>830.0</td>
</tr>
<tr class="data-row">
<td>5</td>
<td>2012-11-18</td>
<td>102</td>
<td>209</td>
<td>7</td>
<td>-67.0</td>
<td>833.0</td>
</tr>
<tr class="data-row">
<td>6</td>
<td>2012-11-19</td>
<td>103</td>
<td>209</td>
<td>7</td>
<td>-66.0</td>
<td>836.0</td>
</tr>
<tr class="data-row">
<td>7</td>
<td>2012-11-20</td>
<td>104</td>
<td>210</td>
<td>8</td>
<td>-67.0</td>
<td>838.0</td>
</tr>
<tr class="data-row">
<td>8</td>
<td>2012-11-21</td>
<td>105</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>839.0</td>
</tr>
<tr class="data-row">
<td>9</td>
<td>2012-11-23</td>
<td>106</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>841.0</td>
</tr>
<tr class="data-row">
<td>10</td>
<td>2012-11-24</td>
<td>107</td>
<td>212</td>
<td>8</td>
<td>-66.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>11</td>
<td>2012-11-25</td>
<td>108</td>
<td>212</td>
<td>8</td>
<td>-65.0</td>
<td>845.0</td>
</tr>
<tr class="data-row">
<td>12</td>
<td>2012-11-26</td>
<td>109</td>
<td>213</td>
<td>8</td>
<td>-64.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>14</td>
<td>2012-11-27</td>
<td>110</td>
<td>214</td>
<td>8</td>
<td>-65.0</td>
<td>848.0</td>
</tr>
<tr class="data-row">
<td>15</td>
<td>2012-11-28</td>
<td>111</td>
<td>214</td>
<td>8</td>
<td>-66.0</td>
<td>849.0</td>
</tr>
<tr class="data-row">
<td>16</td>
<td>2012-11-29</td>
<td>112</td>
<td>215</td>
<td>8</td>
<td>-65.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>17</td>
<td>2012-11-30</td>
<td>113</td>
<td>216</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>18</td>
<td>2012-12-01</td>
<td>114</td>
<td>216</td>
<td>8</td>
<td>-69.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>19</td>
<td>2012-12-02</td>
<td>115</td>
<td>217</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>20</td>
<td>2012-12-03</td>
<td>116</td>
<td>217</td>
<td>8</td>
<td>-67.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>21</td>
<td>2012-12-04</td>
<td>117</td>
<td>218</td>
<td>8</td>
<td>-66.0</td>
<td>861.0</td>
</tr>
<tr class="data-row">
<td>22</td>
<td>2012-12-05</td>
<td>118</td>
<td>219</td>
<td>8</td>
<td>-65.0</td>
<td>864.0</td>
</tr>
<tr class="data-row">
<td>23</td>
<td>2012-12-06</td>
<td>119</td>
<td>219</td>
<td>8</td>
<td>-66.0</td>
<td>866.0</td>
</tr>
<tr class="data-row">
<td>25</td>
<td>2012-12-07</td>
<td>120</td>
<td>220</td>
<td>8</td>
<td>-67.0</td>
<td>867.0</td>
</tr>
<tr class="data-row">
<td>26</td>
<td>2012-12-08</td>
<td>121</td>
<td>221</td>
<td>8</td>
<td>-66.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>27</td>
<td>2012-12-09</td>
<td>122</td>
<td>221</td>
<td>8</td>
<td>-65.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>28</td>
<td>2012-12-10</td>
<td>123</td>
<td>222</td>
<td>8</td>
<td>-66.0</td>
<td>875.0</td>
</tr>
<tr class="data-row">
<td>29</td>
<td>2012-12-11</td>
<td>124</td>
<td>223</td>
<td>8</td>
<td>-66.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>30</td>
<td>2012-12-12</td>
<td>125</td>
<td>223</td>
<td>8</td>
<td>-68.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>31</td>
<td>2012-12-13</td>
<td>126</td>
<td>224</td>
<td>8</td>
<td>-66.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>32</td>
<td>2012-12-14</td>
<td>127</td>
<td>224</td>
<td>8</td>
<td>-67.0</td>
<td>884.0</td>
</tr>
<tr class="data-row">
<td>33</td>
<td>2012-12-15</td>
<td>128</td>
<td>225</td>
<td>8</td>
<td>-67.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>34</td>
<td>2012-12-16</td>
<td>129</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>36</td>
<td>2012-12-17</td>
<td>130</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>37</td>
<td>2012-12-18</td>
<td>131</td>
<td>227</td>
<td>8</td>
<td>-65.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>38</td>
<td>2012-12-19</td>
<td>132</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>39</td>
<td>2012-12-20</td>
<td>133</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>891.0</td>
</tr>
<tr class="data-row">
<td>40</td>
<td>2012-12-21</td>
<td>134</td>
<td>229</td>
<td>8</td>
<td>-67.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>41</td>
<td>2012-12-22</td>
<td>135</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>894.0</td>
</tr>
<tr class="data-row">
<td>42</td>
<td>2012-12-23</td>
<td>136</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>897.0</td>
</tr>
<tr class="data-row">
<td>43</td>
<td>2012-12-24</td>
<td>137</td>
<td>231</td>
<td>8</td>
<td>-64.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>44</td>
<td>2012-12-25</td>
<td>138</td>
<td>232</td>
<td>8</td>
<td>-65.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>45</td>
<td>2012-12-26</td>
<td>139</td>
<td>232</td>
<td>8</td>
<td>-66.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>47</td>
<td>2012-12-27</td>
<td>140</td>
<td>233</td>
<td>8</td>
<td>-66.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>48</td>
<td>2012-12-28</td>
<td>141</td>
<td>233</td>
<td>8</td>
<td>-64.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>49</td>
<td>2012-12-29</td>
<td>142</td>
<td>234</td>
<td>8</td>
<td>-65.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>50</td>
<td>2012-12-31</td>
<td>143</td>
<td>235</td>
<td>8</td>
<td>-63.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>51</td>
<td>2013-01-01</td>
<td>144</td>
<td>235</td>
<td>8</td>
<td>-64.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>52</td>
<td>2013-01-02</td>
<td>145</td>
<td>236</td>
<td>8</td>
<td>-64.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>53</td>
<td>2013-01-03</td>
<td>146</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>54</td>
<td>2013-01-04</td>
<td>147</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>55</td>
<td>2013-01-05</td>
<td>148</td>
<td>238</td>
<td>8</td>
<td>-65.0</td>
<td>912.0</td>
</tr>
<tr class="data-row">
<td>56</td>
<td>2013-01-06</td>
<td>149</td>
<td>239</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>58</td>
<td>2013-01-07</td>
<td>150</td>
<td>239</td>
<td>8</td>
<td>-64.0</td>
<td>913.0</td>
</tr>
<tr class="data-row">
<td>59</td>
<td>2013-01-08</td>
<td>151</td>
<td>240</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>60</td>
<td>2013-01-09</td>
<td>152</td>
<td>241</td>
<td>9</td>
<td>-63.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>61</td>
<td>2013-01-10</td>
<td>153</td>
<td>241</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>62</td>
<td>2013-01-11</td>
<td>154</td>
<td>242</td>
<td>9</td>
<td>-65.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>63</td>
<td>2013-01-12</td>
<td>155</td>
<td>243</td>
<td>9</td>
<td>-64.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>64</td>
<td>2013-01-13</td>
<td>156</td>
<td>243</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>65</td>
<td>2013-01-14</td>
<td>157</td>
<td>244</td>
<td>9</td>
<td>-64.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>66</td>
<td>2013-01-15</td>
<td>158</td>
<td>245</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>67</td>
<td>2013-01-16</td>
<td>159</td>
<td>245</td>
<td>9</td>
<td>-65.0</td>
<td>918.0</td>
</tr>
<tr class="data-row">
<td>69</td>
<td>2013-01-17</td>
<td>160</td>
<td>246</td>
<td>9</td>
<td>-67.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>70</td>
<td>2013-01-18</td>
<td>161</td>
<td>246</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>71</td>
<td>2013-01-19</td>
<td>162</td>
<td>247</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>72</td>
<td>2013-01-20</td>
<td>163</td>
<td>248</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>73</td>
<td>2013-01-21</td>
<td>164</td>
<td>248</td>
<td>9</td>
<td>-64.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>74</td>
<td>2013-01-22</td>
<td>165</td>
<td>249</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>75</td>
<td>2013-01-23</td>
<td>166</td>
<td>250</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>76</td>
<td>2013-01-24</td>
<td>167</td>
<td>250</td>
<td>9</td>
<td>-65.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>77</td>
<td>2013-01-25</td>
<td>168</td>
<td>251</td>
<td>9</td>
<td>-66.0</td>
<td>923.0</td>
</tr>
<tr class="data-row">
<td>78</td>
<td>2013-01-26</td>
<td>169</td>
<td>252</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>80</td>
<td>2013-01-27</td>
<td>170</td>
<td>252</td>
<td>9</td>
<td>-66.0</td>
<td>925.0</td>
</tr>
<tr class="data-row">
<td>81</td>
<td>2013-01-28</td>
<td>171</td>

<tr class="data-row">
<td>1376</td>
<td>2016-09-10</td>
<td>1456</td>
<td>219</td>
<td>8</td>
<td>-69.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>1375</td>
<td>2016-09-11</td>
<td>1457</td>
<td>220</td>
<td>8</td>
<td>-69.0</td>
<td>860.0</td>
</tr>
<tr class="data-row">
<td>1378</td>
<td>2016-09-12</td>
<td>1458</td>
<td>220</td>
<td>8</td>
<td>-69.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>1379</td>
<td>2016-09-13</td>
<td>1459</td>
<td>221</td>
<td>8</td>
<td>-71.0</td>
<td>861.0</td>
</tr>
<tr class="data-row">
<td>1380</td>
<td>2016-09-14</td>
<td>1460</td>
<td>222</td>
<td>8</td>
<td>-70.0</td>
<td>865.0</td>
</tr>
<tr class="data-row">
<td>1382</td>
<td>2016-09-15</td>
<td>1461</td>
<td>222</td>
<td>8</td>
<td>-69.0</td>
<td>870.0</td>
</tr>
<tr class="data-row">
<td>1381</td>
<td>2016-09-16</td>
<td>1462</td>
<td>223</td>
<td>8</td>
<td>-68.0</td>
<td>871.0</td>
</tr>
<tr class="data-row">
<td>1383</td>
<td>2016-09-17</td>
<td>1463</td>
<td>224</td>
<td>8</td>
<td>-68.0</td>
<td>871.0</td>
</tr>
<tr class="data-row">
<td>1384</td>
<td>2016-09-18</td>
<td>1464</td>
<td>224</td>
<td>8</td>
<td>-71.0</td>
<td>871.0</td>
</tr>
<tr class="data-row">
<td>1385</td>
<td>2016-09-19</td>
<td>1465</td>
<td>225</td>
<td>8</td>
<td>-68.0</td>
<td>870.0</td>
</tr>
<tr class="data-row">
<td>1386</td>
<td>2016-09-20</td>
<td>1466</td>
<td>226</td>
<td>8</td>
<td>-67.0</td>
<td>873.0</td>
</tr>
<tr class="data-row">
<td>1387</td>
<td>2016-09-21</td>
<td>1467</td>
<td>226</td>
<td>8</td>
<td>-69.0</td>
<td>877.0</td>
</tr>
<tr class="data-row">
<td>1388</td>
<td>2016-09-22</td>
<td>1468</td>
<td>227</td>
<td>8</td>
<td>-70.0</td>
<td>879.0</td>
</tr>
<tr class="data-row">
<td>1389</td>
<td>2016-09-23</td>
<td>1469</td>
<td>228</td>
<td>8</td>
<td>-72.0</td>
<td>881.0</td>
</tr>
<tr class="data-row">
<td>1391</td>
<td>2016-09-24</td>
<td>1470</td>
<td>228</td>
<td>8</td>
<td>-70.0</td>
<td>879.0</td>
</tr>
<tr class="data-row">
<td>1392</td>
<td>2016-09-25</td>
<td>1471</td>
<td>229</td>
<td>8</td>
<td>-71.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>1390</td>
<td>2016-09-26</td>
<td>1472</td>
<td>229</td>
<td>8</td>
<td>-68.0</td>
<td>879.0</td>
</tr>
<tr class="data-row">
<td>1393</td>
<td>2016-09-27</td>
<td>1473</td>
<td>230</td>
<td>8</td>
<td>-67.0</td>
<td>881.0</td>
</tr>
<tr class="data-row">
<td>1394</td>
<td>2016-09-28</td>
<td>1474</td>
<td>231</td>
<td>8</td>
<td>-68.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>1396</td>
<td>2016-09-29</td>
<td>1475</td>
<td>231</td>
<td>8</td>
<td>-72.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>1395</td>
<td>2016-09-30</td>
<td>1476</td>
<td>232</td>
<td>8</td>
<td>-69.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>1397</td>
<td>2016-10-01</td>
<td>1477</td>
<td>233</td>
<td>8</td>
<td>-72.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>1399</td>
<td>2016-10-02</td>
<td>1478</td>
<td>233</td>
<td>8</td>
<td>-68.0</td>
<td>887.0</td>
</tr>
<tr class="data-row">
<td>1398</td>
<td>2016-10-03</td>
<td>1479</td>
<td>234</td>
<td>8</td>
<td>-66.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>1400</td>
<td>2016-10-04</td>
<td>1480</td>
<td>235</td>
<td>8</td>
<td>-68.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>1401</td>
<td>2016-10-05</td>
<td>1481</td>
<td>235</td>
<td>8</td>
<td>-70.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>1403</td>
<td>2016-10-06</td>
<td>1482</td>
<td>236</td>
<td>8</td>
<td>-68.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>1402</td>
<td>2016-10-07</td>
<td>1483</td>
<td>237</td>
<td>8</td>
<td>-68.0</td>
<td>892.0</td>
</tr>
<tr class="data-row">
<td>1404</td>
<td>2016-10-08</td>
<td>1484</td>
<td>237</td>
<td>8</td>
<td>-68.0</td>
<td>895.0</td>
</tr>
<tr class="data-row">
<td>1405</td>
<td>2016-10-09</td>
<td>1485</td>
<td>238</td>
<td>8</td>
<td>-71.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>1406</td>
<td>2016-10-10</td>
<td>1486</td>
<td>239</td>
<td>8</td>
<td>-71.0</td>
<td>901.0</td>
</tr>
<tr class="data-row">
<td>1407</td>
<td>2016-10-11</td>
<td>1487</td>
<td>239</td>
<td>8</td>
<td>-68.0</td>
<td>901.0</td>
</tr>
<tr class="data-row">
<td>1408</td>
<td>2016-10-12</td>
<td>1488</td>
<td>240</td>
<td>9</td>
<td>-69.0</td>
<td>902.0</td>
</tr>
<tr class="data-row">
<td>1410</td>
<td>2016-10-14</td>
<td>1489</td>
<td>240</td>
<td>9</td>
<td>-68.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>1411</td>
<td>2016-10-15</td>
<td>1490</td>
<td>241</td>
<td>9</td>
<td>-66.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>1409</td>
<td>2016-10-16</td>
<td>1491</td>
<td>242</td>
<td>9</td>
<td>-69.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1412</td>
<td>2016-10-17</td>
<td>1492</td>
<td>242</td>
<td>9</td>
<td>-68.0</td>
<td>910.0</td>
</tr>
<tr class="data-row">
<td>1413</td>
<td>2016-10-18</td>
<td>1493</td>
<td>243</td>
<td>9</td>
<td>-70.0</td>
<td>905.0</td>
</tr>
<tr class="data-row">
<td>1414</td>
<td>2016-10-19</td>
<td>1494</td>
<td>244</td>
<td>9</td>
<td>-70.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>1416</td>
<td>2016-10-20</td>
<td>1495</td>
<td>244</td>
<td>9</td>
<td>-71.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>1415</td>
<td>2016-10-21</td>
<td>1496</td>
<td>245</td>
<td>9</td>
<td>-72.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1417</td>
<td>2016-10-22</td>
<td>1497</td>
<td>246</td>
<td>9</td>
<td>-68.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>1418</td>
<td>2016-10-23</td>
<td>1498</td>
<td>246</td>
<td>9</td>
<td>-68.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1419</td>
<td>2016-10-24</td>
<td>1499</td>
<td>247</td>
<td>9</td>
<td>-69.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>1420</td>
<td>2016-10-25</td>
<td>1500</td>
<td>248</td>
<td>9</td>
<td>-70.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>1421</td>
<td>2016-10-26</td>
<td>1501</td>
<td>248</td>
<td>9</td>
<td>-69.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>1422</td>
<td>2016-10-27</td>
<td>1502</td>
<td>249</td>
<td>9</td>
<td>-69.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1424</td>
<td>2016-10-28</td>
<td>1503</td>
<td>250</td>
<td>9</td>
<td>-70.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>1423</td>
<td>2016-10-29</td>
<td>1504</td>
<td>250</td>
<td>9</td>
<td>-69.0</td>
<td>910.0</td>
</tr>
<tr class="data-row">
<td>1425</td>
<td>2016-10-30</td>
<td>1505</td>
<td>251</td>
<td>9</td>
<td>-69.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1426</td>
<td>2016-10-31</td>
<td>1506</td>
<td>252</td>
<td>9</td>
<td>-71.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1427</td>
<td>2016-11-01</td>
<td>1507</td>
<td>252</td>
<td>9</td>
<td>-70.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1428</td>
<td>2016-11-02</td>
<td>1508</td>
<td>253</td>
<td>9</td>
<td>-70.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1430</td>
<td>2016-11-03</td>
<td>1509</td>
<td>254</td>
<td>9</td>
<td>-70.0</td>
<td>910.0</td>
</tr>
<tr class="data-row">
<td>1431</td>
<td>2016-11-04</td>
<td>1510</td>
<td>254</td>
<td>9</td>
<td>-70.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>1429</td>
<td>2016-11-05</td>
<td>1511</td>
<td>255</td>
<td>9</td>
<td>-77.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>1432</td>
<td>2016-11-06</td>
<td>1512</td>
<td>255</td>
<td>9</td>
<td>-78.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1433</td>
<td>2016-11-07</td>
<td>1513</td>
<td>256</td>
<td>9</td>
<td>-74.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>1434</td>
<td>2016-11-08</td>
<td>1514</td>
<td>257</td>
<td>9</td>
<td>-73.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1435</td>
<td>2016-11-09</td>
<td>1515</td>
<td>257</td>
<td>9</td>
<td>-76.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1436</td>
<td>2016-11-10</td>
<td>1516</td>
<td>258</td>
<td>9</td>
<td>-71.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>1437</td>
<td>2016-11-11</td>
<td>1517</td>
<td>259</td>
<td>9</td>
<td>-76.0</td>
<td>911.0</td>
</tr>
<tr class="data-row">
<td>1438</td>
<td>2016-11-12</td>
<td>1518</td>
<td>259</td>
<td>9</td>
<td>-78.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>1440</td>
<td>2016-11-13</td>
<td>1519</td>
<td>260</td>
<td>9</td>
<td>-72.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>1439</td>
<td>2016-11-14</td>
<td>1520</td>
<td>261</td>
<td>9</td>
<td>-73.0</td>
<td>905.0</td>
</tr>
<tr class="data-row">
<td>1441</td>
<td>2016-11-15</td>
<td>1521</td>
<td>261</td>
<td>9</td>
<td>-71.0</td>
<td>905.0</td>
</tr>
<tr class="data-row">
<td>1442</td>
<td>2016-11-16</td>
<td>1522</td>
<td>262</td>
<td>9</td>
<td>-71.0</td>
<td>905.0</td>
</tr>
<tr class="data-row">
<td>1443</td>
<td>2016-11-17</td>
<td>1523</td>
<td>263</td>
<td>9</td>
<td>-77.0</td>
<td>905.0</td>
</tr>
<tr class="data-row">
<td>1444</td>
<td>2016-11-18</td>
<td>1524</td>
<td>263</td>
<td>9</td>
<td>-76.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>1445</td>
<td>2016-11-20</td>
<td>1525</td>
<td>264</td>
<td>9</td>
<td>-74.0</td>
<td>902.0</td>
</tr>
<tr class="data-row">
<td>1446</td>
<td>2016-11-21</td>
<td>1526</td>
<td>265</td>
<td>9</td>
<td>-72.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1449</td>
<td>2016-11-22</td>
<td>1527</td>
<td>265</td>
<td>9</td>
<td>-71.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1450</td>
<td>2016-11-23</td>
<td>1528</td>
<td>266</td>
<td>9</td>
<td>-72.0</td>
<td>898.0</td>
</tr>
<tr class="data-row">
<td>1451</td>
<td>2016-11-24</td>
<td>1529</td>
<td>267</td>
<td>9</td>
<td>-73.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1452</td>
<td>2016-11-25</td>
<td>1530</td>
<td>267</td>
<td>9</td>
<td>-71.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>1447</td>
<td>2016-11-26</td>
<td>1531</td>
<td>268</td>
<td>9</td>
<td>-76.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1448</td>
<td>2016-11-27</td>
<td>1532</td>
<td>268</td>
<td>9</td>
<td>-72.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1453</td>
<td>2016-11-28</td>
<td>1533</td>
<td>269</td>
<td>9</td>
<td>-72.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>1454</td>
<td>2016-11-29</td>
<td>1534</td>
<td>270</td>
<td>10</td>
<td>-73.0</td>
<td>898.0</td>
</tr>
<tr class="data-row">
<td>1455</td>
<td>2016-11-30</td>
<td>1535</td>
<td>270</td>
<td>10</td>
<td>-73.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1456</td>
<td>2016-12-01</td>
<td>1536</td>
<td>271</td>
<td>10</td>
<td>-71.0</td>
<td>901.0</td>
</tr>
<tr class="data-row">
<td>1458</td>
<td>2016-12-02</td>
<td>1537</td>
<td>272</td>
<td>10</td>
<td>-74.0</td>
<td>900.0</td>
</tr>
<tr class="data-row">
<td>1457</td>
<td>2016-12-03</td>
<td>1538</td>
<td>272</td>
<td>10</td>
<td>-73.0</td>
<td>898.0</td>
</tr>
<tr class="data-row">
<td>1459</td>
<td>2016-12-04</td>
<td>1539</td>
<td>273</td>
<td>10</td>
<td>-74.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>1460</td>
<td>2016-12-05</td>
<td>1540</td>
<td>274</td>
<td>10</td>
<td>-72.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>1461</td>
<td>2016-12-06</td>
<td>1541</td>
<td>274</td>
<td>10</td>
<td>-76.0</td>
<td>895.0</td>
</tr>
<tr class="data-row">
<td>1462</td>
<td>2016-12-07</td>
<td>1542</td>
<td>275</td>
<td>10</td>
<td>-73.0</td>
<td>895.0</td>
</tr>
<tr class="data-row">
<td>1464</td>
<td>2016-12-08</td>
<td>1543</td>
<td>276</td>
<td>10</td>
<td>-74.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>1463</td>
<td>2016-12-09</td>
<td>1544</td>
<td>276</td>
<td>10</td>
<td>-71.0</td>
<td>894.0</td>
</tr>
<tr class="data-row">
<td>1465</td>
<td>2016-12-10</td>
<td>1545</td>
<td>277</td>
<td>10</td>
<td>-73.0</td>
<td>891.0</td>
</tr>
<tr class="data-row">
<td>1467</td>
<td>2016-12-11</td>
<td>1546</td>
<td>277</td>
<td>10</td>
<td>-73.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>1466</td>
<td>2016-12-12</td>
<td>1547</td>
<td>278</td>
<td>10</td>
<td>-75.0</td>
<td>887.0</td>
</tr>
<tr class="data-row">
<td>1468</td>
<td>2016-12-13</td>
<td>1548</td>
<td>279</td>
<td>10</td>
<td>-76.0</td>
<td>887.0</td>
</tr>
<tr class="data-row">
<td>1469</td>
<td>2016-12-14</td>
<td>1549</td>
<td>279</td>
<td>10</td>
<td>-76.0</td>
<td>887.0</td>
</tr>
<tr class="data-row">
<td>1472</td>
<td>2016-12-15</td>
<td>1550</td>
<td>280</td>
<td>10</td>
<td>-71.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>1471</td>
<td>2016-12-16</td>
<td>1551</td>
<td>281</td>
<td>10</td>
<td>-71.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>1470</td>
<td>2016-12-17</td>
<td>1552</td>
<td>281</td>
<td>10</td>
<td>-74.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>1474</td>
<td>2016-12-18</td>
<td>1553</td>
<td>282</td>
<td>10</td>
<td>-77.0</td>
<td>884.0</td>
</tr>
<tr class="data-row">
<td>1473</td>
<td>2016-12-19</td>
<td>1554</td>
<td>283</td>
<td>10</td>
<td>-70.0</td>
<td>882.0</td>
</tr>
<tr class="data-row">
<td>1477</td>
<td>2016-12-20</td>
<td>1555</td>
<td>283</td>
<td>10</td>
<td>-71.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>1478</td>
<td>2016-12-21</td>
<td>1556</td>
<td>284</td>
<td>10</td>
<td>-72.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>1475</td>
<td>2016-12-22</td>
<td>1557</td>
<td>284</td>
<td>10</td>
<td>-70.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>1476</td>
<td>2016-12-23</td>
<td>1558</td>
<td>285</td>
<td>10</td>
<td>-72.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>1484</td>
<td>2016-12-24</td>
<td>1559</td>
<td>286</td>
<td>10</td>
<td>-76.0</td>
<td>879.0</td>
</tr>
<tr class="data-row">
<td>1482</td>
<td>2016-12-25</td>
<td>1560</td>
<td>286</td>
<td>10</td>
<td>-76.0</td>
<td>877.0</td>
</tr>
<tr class="data-row">
<td>1485</td>
<td>2016-12-27</td>
<td>1561</td>
<td>287</td>
<td>10</td>
<td>-77.0</td>
<td>877.0</td>
</tr>
<tr class="data-row">
<td>1479</td>
<td>2016-12-28</td>
<td>1562</td>
<td>288</td>
<td>10</td>
<td>-73.0</td>
<td>877.0</td>
</tr>
<tr class="data-row">
<td>1483</td>
<td>2016-12-29</td>
<td>1563</td>
<td>288</td>
<td>10</td>
<td>-75.0</td>
<td>879.0</td>
</tr>
<tr class="data-row">
<td>1481</td>
<td>2016-12-30</td>
<td>1564</td>
<td>289</td>
<td>10</td>
<td>-70.0</td>
<td>877.0</td>
</tr>
<tr class="data-row">
<td>1480</td>
<td>2016-12-31</td>
<td>1565</td>
<td>290</td>
<td>10</td>
<td>-72.0</td>
<td>874.0</td>
</tr>
<tr class="data-row">
<td>1487</td>
<td>2017-01-01</td>
<td>1566</td>
<td>290</td>
<td>10</td>
<td>-76.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>1486</td>
<td>2017-01-02</td>
<td>1567</td>
<td>291</td>
<td>10</td>
<td>-70.0</td>
<td>872.0</td>
</tr>
<tr class="data-row">
<td>1488</td>
<td>2017-01-03</td>
<td>1568</td>
<td>291</td>
<td>10</td>
<td>-71.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>1492</td>
<td>2017-01-04</td>
<td>1569</td>
<td>292</td>
<td>10</td>
<td>-70.0</td>
<td>873.0</td>
</tr>
<tr class="data-row">
<td>1491</td>
<td>2017-01-05</td>
<td>1570</td>
<td>293</td>
<td>10</td>
<td>-71.0</td>
<td>873.0</td>
</tr>
<tr class="data-row">
<td>1490</td>
<td>2017-01-06</td>
<td>1571</td>
<td>293</td>
<td>10</td>
<td>-70.0</td>
<td>873.0</td>
</tr>
<tr class="data-row">
<td>1489</td>
<td>2017-01-07</td>
<td>1572</td>
<td>294</td>
<td>10</td>
<td>-81.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>1493</td>
<td>2017-01-08</td>
<td>1573</td>
<td>295</td>
<td>10</td>
<td>-74.0</td>
<td>872.0</td>
</tr>
<tr class="data-row">
<td>1495</td>
<td>2017-01-09</td>
<td>1574</td>
<td>295</td>
<td>10</td>
<td>-72.0</td>
<td>868.0</td>
</tr>
<tr class="data-row">
<td>1494</td>
<td>2017-01-10</td>
<td>1575</td>
<td>296</td>
<td>10</td>
<td>-73.0</td>
<td>871.0</td>
</tr>
<tr class="data-row">
<td>1496</td>
<td>2017-01-11</td>
<td>1576</td>
<td>296</td>
<td>10</td>
<td>-72.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>1498</td>
<td>2017-01-12</td>
<td>1577</td>
<td>297</td>
<td>10</td>
<td>-72.0</td>
<td>866.0</td>
</tr>
<tr class="data-row">
<td>1499</td>
<td>2017-01-13</td>
<td>1578</td>
<td>298</td>
<td>10</td>
<td>-74.0</td>
<td>868.0</td>
</tr>
<tr class="data-row">
<td>1500</td>
<td>2017-01-14</td>
<td>1579</td>
<td>298</td>
<td>10</td>
<td>-73.0</td>
<td>862.0</td>
</tr>
<tr class="data-row">
<td>1497</td>
<td>2017-01-15</td>
<td>1580</td>
<td>299</td>
<td>10</td>
<td>-72.0</td>
<td>867.0</td>
</tr>
<tr class="data-row">
<td>1501</td>
<td>2017-01-16</td>
<td>1581</td>
<td>299</td>
<td>10</td>
<td>-72.0</td>
<td>862.0</td>
</tr>
<tr class="data-row">
<td>1503</td>
<td>2017-01-17</td>
<td>1582</td>
<td>300</td>
<td>11</td>
<td>-74.0</td>
<td>862.0</td>
</tr>
<tr class="data-row">
<td>1502</td>
<td>2017-01-18</td>
<td>1583</td>
<td>301</td>
<td>11</td>
<td>-75.0</td>
<td>862.0</td>
</tr>
<tr class="data-row">
<td>1505</td>
<td>2017-01-19</td>
<td>1584</td>
<td>301</td>
<td>11</td>
<td>-77.0</td>
<td>860.0</td>
</tr>
<tr class="data-row">
<td>1506</td>
<td>2017-01-20</td>
<td>1585</td>
<td>302</td>
<td>11</td>
<td>-76.0</td>
<td>864.0</td>
</tr>
<tr class="data-row">
<td>1504</td>
<td>2017-01-21</td>
<td>1586</td>
<td>303</td>
<td>11</td>
<td>-72.0</td>
<td>858.0</td>
</tr>
<tr class="data-row">
<td>1508</td>
<td>2017-01-22</td>
<td>1587</td>
<td>303</td>
<td>11</td>
<td>-73.0</td>
<td>860.0</td>
</tr>
<tr class="data-row">
<td>1507</td>
<td>2017-01-23</td>
<td>1588</td>
<td>304</td>
<td>11</td>
<td>-72.0</td>
<td>858.0</td>
</tr>
<tr class="data-row">
<td>1510</td>
<td>2017-01-24</td>
<td>1589</td>
<td>304</td>
<td>11</td>
<td>-72.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>1509</td>
<td>2017-01-25</td>
<td>1590</td>
<td>305</td>
<td>11</td>
<td>-76.0</td>
<td>860.0</td>
</tr>
<tr class="data-row">
<td>1512</td>
<td>2017-01-26</td>
<td>1591</td>
<td>306</td>
<td>11</td>
<td>-73.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>1511</td>
<td>2017-01-27</td>
<td>1592</td>
<td>306</td>
<td>11</td>
<td>-71.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>1513</td>
<td>2017-01-28</td>
<td>1593</td>
<td>307</td>
<td>11</td>
<td>-72.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>1514</td>
<td>2017-01-29</td>
<td>1594</td>
<td>307</td>
<td>11</td>
<td>-74.0</td>
<td>855.0</td>
</tr>
<tr class="data-row">
<td>1515</td>
<td>2017-01-30</td>
<td>1595</td>
<td>308</td>
<td>11</td>
<td>-71.0</td>
<td>855.0</td>
</tr>
<tr class="data-row">
<td>1516</td>
<td>2017-01-31</td>
<td>1596</td>
<td>309</td>
<td>11</td>
<td>-74.0</td>
<td>850.0</td>
</tr>
<tr class="data-row">
<td>1517</td>
<td>2017-02-01</td>
<td>1597</td>
<td>309</td>
<td>11</td>
<td>-73.0</td>
<td>855.0</td>
</tr>
<tr class="data-row">
<td>1519</td>
<td>2017-02-03</td>
<td>1598</td>
<td>310</td>
<td>11</td>
<td>-70.0</td>
<td>849.0</td>
</tr>
<tr class="data-row">
<td>1518</td>
<td>2017-02-04</td>
<td>1599</td>
<td>310</td>
<td>11</td>
<td>-72.0</td>
<td>853.0</td>
</tr>
<tr class="data-row">
<td>1520</td>
<td>2017-02-05</td>
<td>1600</td>
<td>311</td>
<td>11</td>
<td>-71.0</td>
<td>850.0</td>
</tr>
<tr class="data-row">
<td>1522</td>
<td>2017-02-06</td>
<td>1601</td>
<td>312</td>
<td>11</td>
<td>-71.0</td>
<td>853.0</td>
</tr>
<tr class="data-row">
<td>1521</td>
<td>2017-02-07</td>
<td>1602</td>
<td>312</td>
<td>11</td>
<td>-77.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>1523</td>
<td>2017-02-08</td>
<td>1603</td>
<td>313</td>
<td>11</td>
<td>-76.0</td>
<td>847.0</td>
</tr>
<tr class="data-row">
<td>1524</td>
<td>2017-02-09</td>
<td>1604</td>
<td>313</td>
<td>11</td>
<td>-77.0</td>
<td>850.0</td>
</tr>
<tr class="data-row">
<td>1526</td>
<td>2017-02-10</td>
<td>1605</td>
<td>314</td>
<td>11</td>
<td>-73.0</td>
<td>846.0</td>
</tr>
<tr class="data-row">
<td>1525</td>
<td>2017-02-11</td>
<td>1606</td>
<td>315</td>
<td>11</td>
<td>-75.0</td>
<td>850.0</td>
</tr>
<tr class="data-row">
<td>1528</td>
<td>2017-02-12</td>
<td>1607</td>
<td>315</td>
<td>11</td>
<td>-77.0</td>
<td>846.0</td>
</tr>
<tr class="data-row">
<td>1527</td>
<td>2017-02-13</td>
<td>1608</td>
<td>316</td>
<td>11</td>
<td>-72.0</td>
<td>847.0</td>
</tr>
<tr class="data-row">

### Step 3: Store the Data

Assemble the scraped data into a Pandas DataFrame. The columns should have the same headings as the table on the website. Here’s an explanation of the column headings:

* `id`: the identification number of a single transmission from the Curiosity rover
* `terrestrial_date`: the date on Earth
* `sol`: the number of elapsed sols (Martian days) since Curiosity landed on Mars
* `ls`: the solar longitude
* `month`: the Martian month
* `min_temp`: the minimum temperature, in Celsius, of a single Martian day (sol)
* `pressure`: The atmospheric pressure at Curiosity's location

In [6]:
# Create an empty list
table_list = []

# Loop through the scraped data to create a list of rows
for row in table:
    data = row.find_all('td')  
    if data:  
        data_dict = {
            'id': data[0].text,
            'terrestrial_date': data[1].text,
            'sol': data[2].text,
            'longitude': data[3].text,
            'month': data[4].text,
            'min_temp': data[5].text,
            'pressure': data[6].text}
        table_list.append(data_dict)

pprint(table_list)

[{'id': '2',
  'longitude': '155',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '739.0',
  'sol': '10',
  'terrestrial_date': '2012-08-16'},
 {'id': '13',
  'longitude': '156',
  'min_temp': '-76.0',
  'month': '6',
  'pressure': '740.0',
  'sol': '11',
  'terrestrial_date': '2012-08-17'},
 {'id': '24',
  'longitude': '156',
  'min_temp': '-76.0',
  'month': '6',
  'pressure': '741.0',
  'sol': '12',
  'terrestrial_date': '2012-08-18'},
 {'id': '35',
  'longitude': '157',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '732.0',
  'sol': '13',
  'terrestrial_date': '2012-08-19'},
 {'id': '46',
  'longitude': '157',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '740.0',
  'sol': '14',
  'terrestrial_date': '2012-08-20'},
 {'id': '57',
  'longitude': '158',
  'min_temp': '-78.0',
  'month': '6',
  'pressure': '740.0',
  'sol': '15',
  'terrestrial_date': '2012-08-21'},
 {'id': '68',
  'longitude': '158',
  'min_temp': '-77.0',
  'month': '6',
  'pressure': '740.0',
  'sol': '16',
  'terrestrial_date': '2012-08-22'},
 {'id': '79',
  'longitude': '159',
  'min_temp': '-76.0',
  'month': '6',
  'pressure': '742.0',
  'sol': '17',
  'terrestrial_date': '2012-08-23'},
 {'id': '112',
  'longitude': '161',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '741.0',
  'sol': '21',
  'terrestrial_date': '2012-08-27'},
 {'id': '114',
  'longitude': '162',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '742.0',
  'sol': '22',
  'terrestrial_date': '2012-08-28'},
 {'id': '123',
  'longitude': '162',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '741.0',
  'sol': '23',
  'terrestrial_date': '2012-08-29'},
 {'id': '134',
  'longitude': '163',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '742.0',
  'sol': '24',
  'terrestrial_date': '2012-08-30'},
 {'id': '145',
  'longitude': '163',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '743.0',
  'sol': '25',
  'terrestrial_date': '2012-08-31'},
 {'id': '156',
  'longitude': '164',
  'min_temp': '-76.0',
  'month': '6',
  'pressure': '745.0',
  'sol': '26',
  'terrestrial_date': '2012-09-01'},
 {'id': '163',
  'longitude': '164',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '743.0',
  'sol': '27',
  'terrestrial_date': '2012-09-02'},
 {'id': '170',
  'longitude': '165',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '745.0',
  'sol': '28',
  'terrestrial_date': '2012-09-03'},
 {'id': '171',
  'longitude': '166',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '747.0',
  'sol': '29',
  'terrestrial_date': '2012-09-04'},
 {'id': '172',
  'longitude': '166',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '747.0',
  'sol': '30',
  'terrestrial_date': '2012-09-05'},
 {'id': '173',
  'longitude': '167',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '745.0',
  'sol': '31',
  'terrestrial_date': '2012-09-06'},
 {'id': '175',
  'longitude': '168',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '748.0',
  'sol': '33',
  'terrestrial_date': '2012-09-08'},
 {'id': '176',
  'longitude': '168',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '748.0',
  'sol': '34',
  'terrestrial_date': '2012-09-10'},
 {'id': '177',
  'longitude': '169',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '749.0',
  'sol': '35',
  'terrestrial_date': '2012-09-11'},
 {'id': '178',
  'longitude': '169',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '750.0',
  'sol': '36',
  'terrestrial_date': '2012-09-12'},
 {'id': '179',
  'longitude': '170',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '750.0',
  'sol': '37',
  'terrestrial_date': '2012-09-13'},
 {'id': '180',
  'longitude': '171',
  'min_temp': '-73.0',
  'month': '6',
  'pressure': '750.0',
  'sol': '38',
  'terrestrial_date': '2012-09-14'},
 {'id': '181',
  'longitude': '171',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '751.0',
  'sol': '39',
  'terrestrial_date': '2012-09-15'},
 {'id': '182',
  'longitude': '172',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '753.0',
  'sol': '40',
  'terrestrial_date': '2012-09-16'},
 {'id': '183',
  'longitude': '172',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '753.0',
  'sol': '41',
  'terrestrial_date': '2012-09-17'},
 {'id': '184',
  'longitude': '173',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '754.0',
  'sol': '42',
  'terrestrial_date': '2012-09-18'},
 {'id': '185',
  'longitude': '173',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '756.0',
  'sol': '43',
  'terrestrial_date': '2012-09-19'},
 {'id': '186',
  'longitude': '174',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '757.0',
  'sol': '44',
  'terrestrial_date': '2012-09-20'},
 {'id': '187',
  'longitude': '175',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '758.0',
  'sol': '45',
  'terrestrial_date': '2012-09-21'},
 {'id': '188',
  'longitude': '175',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '758.0',
  'sol': '46',
  'terrestrial_date': '2012-09-22'},
 {'id': '189',
  'longitude': '176',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '758.0',
  'sol': '47',
  'terrestrial_date': '2012-09-23'},
 {'id': '190',
  'longitude': '176',
  'min_temp': '-75.0',
  'month': '6',
  'pressure': '759.0',
  'sol': '48',
  'terrestrial_date': '2012-09-24'},
 {'id': '191',
  'longitude': '177',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '761.0',
  'sol': '49',
  'terrestrial_date': '2012-09-25'},
 {'id': '192',
  'longitude': '177',
  'min_temp': '-72.0',
  'month': '6',
  'pressure': '761.0',
  'sol': '50',
  'terrestrial_date': '2012-09-26'},
 {'id': '193',
  'longitude': '178',
  'min_temp': '-76.0',
  'month': '6',
  'pressure': '762.0',
  'sol': '51',
  'terrestrial_date': '2012-09-27'},
 {'id': '194',
  'longitude': '179',
  'min_temp': '-74.0',
  'month': '6',
  'pressure': '762.0',
  'sol': '52',
  'terrestrial_date': '2012-09-28'},
 {'id': '195',
  'longitude': '179',
  'min_temp': '-71.0',
  'month': '6',
  'pressure': '764.0',
  'sol': '53',
  'terrestrial_date': '2012-09-29'},
 {'id': '196',
  'longitude': '180',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '766.0',
  'sol': '54',
  'terrestrial_date': '2012-09-30'},
 {'id': '197',
  'longitude': '180',
  'min_temp': '-74.0',
  'month': '7',
  'pressure': '766.0',
  'sol': '55',
  'terrestrial_date': '2012-10-01'},
 {'id': '198',
  'longitude': '181',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '768.0',
  'sol': '56',
  'terrestrial_date': '2012-10-02'},
 {'id': '199',
  'longitude': '181',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '769.0',
  'sol': '57',
  'terrestrial_date': '2012-10-03'},
 {'id': '200',
  'longitude': '182',
  'min_temp': '-74.0',
  'month': '7',
  'pressure': '769.0',
  'sol': '58',
  'terrestrial_date': '2012-10-04'},
 {'id': '201',
  'longitude': '183',
  'min_temp': '-76.0',
  'month': '7',
  'pressure': '771.0',
  'sol': '59',
  'terrestrial_date': '2012-10-05'},
 {'id': '202',
  'longitude': '183',
  'min_temp': '-75.0',
  'month': '7',
  'pressure': '772.0',
  'sol': '60',
  'terrestrial_date': '2012-10-06'},
 {'id': '203',
  'longitude': '184',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '772.0',
  'sol': '61',
  'terrestrial_date': '2012-10-07'},
 {'id': '204',
  'longitude': '184',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '774.0',
  'sol': '62',
  'terrestrial_date': '2012-10-08'},
 {'id': '205',
  'longitude': '185',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '775.0',
  'sol': '63',
  'terrestrial_date': '2012-10-09'},
 {'id': '206',
  'longitude': '186',
  'min_temp': '-74.0',
  'month': '7',
  'pressure': '776.0',
  'sol': '64',
  'terrestrial_date': '2012-10-10'},
 {'id': '207',
  'longitude': '186',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '777.0',
  'sol': '65',
  'terrestrial_date': '2012-10-11'},
 {'id': '208',
  'longitude': '187',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '778.0',
  'sol': '66',
  'terrestrial_date': '2012-10-12'},
 {'id': '209',
  'longitude': '187',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '780.0',
  'sol': '67',
  'terrestrial_date': '2012-10-13'},
 {'id': '210',
  'longitude': '188',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '781.0',
  'sol': '68',
  'terrestrial_date': '2012-10-14'},
 {'id': '211',
  'longitude': '189',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '778.0',
  'sol': '69',
  'terrestrial_date': '2012-10-15'},
 {'id': '212',
  'longitude': '189',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '783.0',
  'sol': '70',
  'terrestrial_date': '2012-10-17'},
 {'id': '213',
  'longitude': '190',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '784.0',
  'sol': '71',
  'terrestrial_date': '2012-10-18'},
 {'id': '214',
  'longitude': '190',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '785.0',
  'sol': '72',
  'terrestrial_date': '2012-10-19'},
 {'id': '215',
  'longitude': '191',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '788.0',
  'sol': '73',
  'terrestrial_date': '2012-10-20'},
 {'id': '216',
  'longitude': '192',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '790.0',
  'sol': '74',
  'terrestrial_date': '2012-10-21'},
 {'id': '217',
  'longitude': '192',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '791.0',
  'sol': '75',
  'terrestrial_date': '2012-10-22'},
 {'id': '218',
  'longitude': '193',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '792.0',
  'sol': '76',
  'terrestrial_date': '2012-10-23'},
 {'id': '219',
  'longitude': '193',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '792.0',
  'sol': '77',
  'terrestrial_date': '2012-10-24'},
 {'id': '220',
  'longitude': '194',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '793.0',
  'sol': '78',
  'terrestrial_date': '2012-10-25'},
 {'id': '221',
  'longitude': '195',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '795.0',
  'sol': '79',
  'terrestrial_date': '2012-10-26'},
 {'id': '222',
  'longitude': '195',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '796.0',
  'sol': '80',
  'terrestrial_date': '2012-10-27'},
 {'id': '223',
  'longitude': '196',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '798.0',
  'sol': '81',
  'terrestrial_date': '2012-10-28'},
 {'id': '224',
  'longitude': '196',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '799.0',
  'sol': '82',
  'terrestrial_date': '2012-10-29'},
 {'id': '225',
  'longitude': '197',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '801.0',
  'sol': '83',
  'terrestrial_date': '2012-10-30'},
 {'id': '226',
  'longitude': '198',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '801.0',
  'sol': '84',
  'terrestrial_date': '2012-10-31'},
 {'id': '227',
  'longitude': '198',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '805.0',
  'sol': '85',
  'terrestrial_date': '2012-11-01'},
 {'id': '228',
  'longitude': '199',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '808.0',
  'sol': '86',
  'terrestrial_date': '2012-11-02'},
 {'id': '229',
  'longitude': '199',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '808.0',
  'sol': '87',
  'terrestrial_date': '2012-11-03'},
 {'id': '230',
  'longitude': '200',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '811.0',
  'sol': '88',
  'terrestrial_date': '2012-11-04'},
 {'id': '231',
  'longitude': '201',
  'min_temp': '-73.0',
  'month': '7',
  'pressure': '813.0',
  'sol': '89',
  'terrestrial_date': '2012-11-05'},
 {'id': '233',
  'longitude': '201',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '813.0',
  'sol': '90',
  'terrestrial_date': '2012-11-06'},
 {'id': '234',
  'longitude': '202',
  'min_temp': '-74.0',
  'month': '7',
  'pressure': '817.0',
  'sol': '91',
  'terrestrial_date': '2012-11-07'},
 {'id': '235',
  'longitude': '202',
  'min_temp': '-74.0',
  'month': '7',
  'pressure': '820.0',
  'sol': '92',
  'terrestrial_date': '2012-11-08'},
 {'id': '236',
  'longitude': '203',
  'min_temp': '-72.0',
  'month': '7',
  'pressure': '819.0',
  'sol': '93',
  'terrestrial_date': '2012-11-09'},
 {'id': '237',
  'longitude': '204',
  'min_temp': '-70.0',
  'month': '7',
  'pressure': '822.0',
  'sol': '94',
  'terrestrial_date': '2012-11-10'},
 {'id': '238',
  'longitude': '204',
  'min_temp': '-68.0',
  'month': '7',
  'pressure': '822.0',
  'sol': '95',
  'terrestrial_date': '2012-11-11'},
 {'id': '239',
  'longitude': '205',
  'min_temp': '-71.0',
  'month': '7',
  'pressure': '826.0',
  'sol': '96',
  'terrestrial_date': '2012-11-12'},
 {'id': '240',
  'longitude': '206',
  'min_temp': '-68.0',
  'month': '7',
  'pressure': '828.0',
  'sol': '97',
  'terrestrial_date': '2012-11-13'},
 {'id': '241',
  'longitude': '206',
  'min_temp': '-68.0',
  'month': '7',
  'pressure': '828.0',
  'sol': '98',
  'terrestrial_date': '2012-11-14'},
 {'id': '242',
  'longitude': '207',
  'min_temp': '-68.0',
  'month': '7',
  'pressure': '829.0',
  'sol': '99',
  'terrestrial_date': '2012-11-15'},
 {'id': '3',
  'longitude': '207',
  'min_temp': '-66.0',
  'month': '7',
  'pressure': '829.0',
  'sol': '100',
  'terrestrial_date': '2012-11-16'},
 {'id': '4',
  'longitude': '208',
  'min_temp': '-65.0',
  'month': '7',
  'pressure': '830.0',
  'sol': '101',
  'terrestrial_date': '2012-11-17'},
 {'id': '5',
  'longitude': '209',
  'min_temp': '-67.0',
  'month': '7',
  'pressure': '833.0',
  'sol': '102',
  'terrestrial_date': '2012-11-18'},
 {'id': '6',
  'longitude': '209',
  'min_temp': '-66.0',
  'month': '7',
  'pressure': '836.0',
  'sol': '103',
  'terrestrial_date': '2012-11-19'},
 {'id': '7',
  'longitude': '210',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '838.0',
  'sol': '104',
  'terrestrial_date': '2012-11-20'},
 {'id': '8',
  'longitude': '211',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '839.0',
  'sol': '105',
  'terrestrial_date': '2012-11-21'},
 {'id': '9',
  'longitude': '211',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '841.0',
  'sol': '106',
  'terrestrial_date': '2012-11-23'},
 {'id': '10',
  'longitude': '212',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '844.0',
  'sol': '107',
  'terrestrial_date': '2012-11-24'},
 {'id': '11',
  'longitude': '212',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '845.0',
  'sol': '108',
  'terrestrial_date': '2012-11-25'},
 {'id': '12',
  'longitude': '213',
  'min_temp': '-64.0',
  'month': '8',
  'pressure': '844.0',
  'sol': '109',
  'terrestrial_date': '2012-11-26'},
 {'id': '14',
  'longitude': '214',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '848.0',
  'sol': '110',
  'terrestrial_date': '2012-11-27'},
 {'id': '15',
  'longitude': '214',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '849.0',
  'sol': '111',
  'terrestrial_date': '2012-11-28'},
 {'id': '16',
  'longitude': '215',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '852.0',
  'sol': '112',
  'terrestrial_date': '2012-11-29'},
 {'id': '17',
  'longitude': '216',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '857.0',
  'sol': '113',
  'terrestrial_date': '2012-11-30'},
 {'id': '18',
  'longitude': '216',
  'min_temp': '-69.0',
  'month': '8',
  'pressure': '857.0',
  'sol': '114',
  'terrestrial_date': '2012-12-01'},
 {'id': '19',
  'longitude': '217',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '857.0',
  'sol': '115',
  'terrestrial_date': '2012-12-02'},
 {'id': '20',
  'longitude': '217',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '859.0',
  'sol': '116',
  'terrestrial_date': '2012-12-03'},
 {'id': '21',
  'longitude': '218',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '861.0',
  'sol': '117',
  'terrestrial_date': '2012-12-04'},
 {'id': '22',
  'longitude': '219',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '864.0',
  'sol': '118',
  'terrestrial_date': '2012-12-05'},
 {'id': '23',
  'longitude': '219',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '866.0',
  'sol': '119',
  'terrestrial_date': '2012-12-06'},
 {'id': '25',
  'longitude': '220',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '867.0',
  'sol': '120',
  'terrestrial_date': '2012-12-07'},
 {'id': '26',
  'longitude': '221',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '869.0',
  'sol': '121',
  'terrestrial_date': '2012-12-08'},
 {'id': '27',
  'longitude': '221',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '869.0',
  'sol': '122',
  'terrestrial_date': '2012-12-09'},
 {'id': '28',
  'longitude': '222',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '875.0',
  'sol': '123',
  'terrestrial_date': '2012-12-10'},
 {'id': '29',
  'longitude': '223',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '876.0',
  'sol': '124',
  'terrestrial_date': '2012-12-11'},
 {'id': '30',
  'longitude': '223',
  'min_temp': '-68.0',
  'month': '8',
  'pressure': '880.0',
  'sol': '125',
  'terrestrial_date': '2012-12-12'},
 {'id': '31',
  'longitude': '224',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '880.0',
  'sol': '126',
  'terrestrial_date': '2012-12-13'},
 {'id': '32',
  'longitude': '224',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '884.0',
  'sol': '127',
  'terrestrial_date': '2012-12-14'},
 {'id': '33',
  'longitude': '225',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '883.0',
  'sol': '128',
  'terrestrial_date': '2012-12-15'},
 {'id': '34',
  'longitude': '226',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '886.0',
  'sol': '129',
  'terrestrial_date': '2012-12-16'},
 {'id': '36',
  'longitude': '226',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '888.0',
  'sol': '130',
  'terrestrial_date': '2012-12-17'},
 {'id': '37',
  'longitude': '227',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '889.0',
  'sol': '131',
  'terrestrial_date': '2012-12-18'},
 {'id': '38',
  'longitude': '228',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '890.0',
  'sol': '132',
  'terrestrial_date': '2012-12-19'},
 {'id': '39',
  'longitude': '228',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '891.0',
  'sol': '133',
  'terrestrial_date': '2012-12-20'},
 {'id': '40',
  'longitude': '229',
  'min_temp': '-67.0',
  'month': '8',
  'pressure': '893.0',
  'sol': '134',
  'terrestrial_date': '2012-12-21'},
 {'id': '41',
  'longitude': '230',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '894.0',
  'sol': '135',
  'terrestrial_date': '2012-12-22'},
 {'id': '42',
  'longitude': '230',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '897.0',
  'sol': '136',
  'terrestrial_date': '2012-12-23'},
 {'id': '43',
  'longitude': '231',
  'min_temp': '-64.0',
  'month': '8',
  'pressure': '896.0',
  'sol': '137',
  'terrestrial_date': '2012-12-24'},
 {'id': '44',
  'longitude': '232',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '899.0',
  'sol': '138',
  'terrestrial_date': '2012-12-25'},
 {'id': '45',
  'longitude': '232',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '899.0',
  'sol': '139',
  'terrestrial_date': '2012-12-26'},
 {'id': '47',
  'longitude': '233',
  'min_temp': '-66.0',
  'month': '8',
  'pressure': '903.0',
  'sol': '140',
  'terrestrial_date': '2012-12-27'},
 {'id': '48',
  'longitude': '233',
  'min_temp': '-64.0',
  'month': '8',
  'pressure': '904.0',
  'sol': '141',
  'terrestrial_date': '2012-12-28'},
 {'id': '49',
  'longitude': '234',
  'min_temp': '-65.0',
  'month': '8',
  'pressure': '906.0',
  'sol': '142',
  'terrestrial_date': '2012-12-29'},
 {'id': '50',
  'longitude': '235',
  'min_temp': '-63.0',
  'month': '8',
  'pressure': '908.0',
  'sol': '143',
  'terrestrial_date': '2012-12-31'},
 {'id': '51',
  'longitude': '235',
  'min_temp': '-64.0',
  'month': '8',
  'pressure': '907.0',
  'sol': '144',
  'terrestrial_date': '2013-01-01'},
 {'id': '52',
  'longitude': '236',
  'min_temp': '-64.0',
  'month': '8',
  'pressure': '909.0',
  'sol': '145',
  'terrestrial_date': '2013-01-02'},
 {'id': '53',
  'longitude': '237',
  'min_temp': '-65.0',
  'month': '8',

In [7]:
# Create a Pandas DataFrame by using the list of rows and a list of the column names
table_df = pd.DataFrame(table_list)

In [8]:
# Confirm DataFrame was created successfully
table_df

        id terrestrial_date   sol longitude month min_temp pressure
0        2       2012-08-16    10       155     6    -75.0    739.0
1       13       2012-08-17    11       156     6    -76.0    740.0
2       24       2012-08-18    12       156     6    -76.0    741.0
3       35       2012-08-19    13       157     6    -74.0    732.0
4       46       2012-08-20    14       157     6    -74.0    740.0
...    ...              ...   ...       ...   ...      ...      ...
1862  1889       2018-02-23  1973       133     5    -78.0    730.0
1863  1892       2018-02-24  1974       134     5    -77.0    729.0
1864  1894       2018-02-25  1975       134     5    -76.0    729.0
1865  1893       2018-02-26  1976       135     5    -77.0    728.0
1866  1895       2018-02-27  1977       135     5    -77.0    727.0

[1867 rows x 7 columns]

### Step 4: Prepare Data for Analysis

Examine the data types that are currently associated with each column. If necessary, cast (or convert) the data to the appropriate `datetime`, `int`, or `float` data types.

  > **Hint** You can use the Pandas `astype` and `to_datetime` methods to accomplish this task.

In [9]:
# Examine data type of each column
print(table_df.dtypes)

id                  object
terrestrial_date    object
sol                 object
longitude           object
month               object
min_temp            object
pressure            object
dtype: object

In [58]:
# # Change data types for data analysis
new_table = table_df.astype({'id':int,'sol':int,'longitude':int,'min_temp':float,'pressure':float})
new_table['terrestrial_date'] = pd.to_datetime(table_df['terrestrial_date'])

In [59]:
# Confirm type changes were successful by examining data types again
new_table.dtypes

id                           int32
terrestrial_date    datetime64[ns]
sol                          int32
longitude                    int32
month                       object
min_temp                   float64
pressure                   float64
dtype: object

### Step 5: Analyze the Data

Analyze your dataset by using Pandas functions to answer the following questions:

1. How many months exist on Mars?
2. How many Martian (and not Earth) days worth of data exist in the scraped dataset?
3. What are the coldest and the warmest months on Mars (at the location of Curiosity)? To answer this question:
    * Find the average the minimum daily temperature for all of the months.
    * Plot the results as a bar chart.
4. Which months have the lowest and the highest atmospheric pressure on Mars? To answer this question:
    * Find the average the daily atmospheric pressure of all the months.
    * Plot the results as a bar chart.
5. About how many terrestrial (Earth) days exist in a Martian year? To answer this question:
    * Consider how many days elapse on Earth in the time that Mars circles the Sun once.
    * Visually estimate the result by plotting the daily minimum temperature.

In [74]:
# 1. How many months are there on Mars?
month_counts = new_table.groupby('month').size().sort_values()
month_counts

month
10    112
9     134
11    138
8     141
7     142
6     147
5     149
12    166
1     174
2     178
3     192
4     194
dtype: int64

In [81]:
# 2. How many Martian days' worth of data are there?
new_table['sol'].max() - new_table['sol'].min()

1967

In [ ]:
# 3. What is the average low temperature by month?

In [ ]:
# Plot the average temperature by month

In [ ]:
# Identify the coldest and hottest months in Curiosity's location

In [ ]:
# 4. Average pressure by Martian month

In [ ]:
# Plot the average pressure by month

In [ ]:
# 5. How many terrestrial (earth) days are there in a Martian year?

On average, the third month has the coldest minimum temperature on Mars, and the eighth month is the warmest. But it is always very cold there in human terms!

Atmospheric pressure is, on average, lowest in the sixth month and highest in the ninth.

The distance from peak to peak is roughly 1425-750, or 675 days. A year on Mars appears to be about 675 days from the plot. Internet search confirms that a Mars year is equivalent to 687 earth days.

### Step 6: Save the Data

Export the DataFrame to a CSV file.

In [ ]:
# Write the data to a CSV

In [ ]:
browser.quit()